### ISSUE TITLE
Issue related to Graded Assignment on Arrays and objects in JS

### ISSUE THREAD

**Issue by Sohailongithub** [snehal-herovired/FSD-11#3]
ASSIGNMENT ON 
Graded Assignment on Arrays and Objects in JS need to get extend because we have not cover the JS topic as per the assignment due date. It need to be postpone below is the assignment link 
https://vlearn.herovired.com/mod/assign/view.php?id=50054&token=

**Comment by snehal-herovired** [comment]
This ticket is already given for the process

**Comment by snehal-herovired** [comment]
Ticket has been resolved

**Comment by Sohailongithub** [comment]
Hi The date has extended to 28/10/2023 but the topics are not covered yet so please extend it to next week

**Comment by noload** [comment]
Hii Snehal, 
Assignment date  still not extended. Kindly do the neeful.

**Comment by snehal-herovired** [comment]
ok sure
